name: Solidity Coverage

on:
  push:
    branches:
      - master
    paths:
      - 'contracts/**'
      - '.github/workflows/solidity-coverage.yml'
  pull_request:
    paths:
      - 'contracts/**'
      - '.github/workflows/solidity-coverage.yml'
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      test_dir: .
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g solhint
    - run: solhint "contracts/*.sol"
      working-directory: ${{ env.test_dir }}
    - run: npm i -g ganache-cli truffle
    - run: npm ci
      working-directory: ${{ env.test_dir }}
    - name: Generate coverage information
      run: truffle run coverage
      working-directory: ${{ env.test_dir }}
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info
