name: Solidity CI

on:
  push:
    paths:
      - 'contracts/**'
      - '.github/workflows/solidity.yml'
  pull_request:
    paths:
      - 'contracts/**'
      - '.github/workflows/solidity.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    env:
      test_dir: .
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g solhint
    - run: solhint "contracts/*.sol"
      working-directory: ${{ env.test_dir }}
    - run: npm i -g ganache-cli truffle
    - run: npm ci
      working-directory: ${{ env.test_dir }}
    - name: test
      run: |
        ganache-cli -p 7545 &
        truffle test
      working-directory: ${{ env.test_dir }}
